controller:
  config:
    log-format-escape-json: "true"
    log-format-upstream: '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "status": "$status", "request": "$request"}'
  metrics:
    enabled: true
